sudo: required
services:
 - docker

before_install:
 - docker build -t henrykizdebski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true henrykizdebski/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-446518935327"
  bucket_path: "docker"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker2"
  env: "docker2-env"
  bucket_name: "elasticbeanstalk-us-east-2-446518935327"
  bucket_path: "docker2"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

